name: Tests

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read       # Required for actions/checkout
  checks:   write      # Required for GitHub Checks API

jobs:
  benchmark-tests:
    if: github.event_name != 'push' && github.ref != 'refs/heads/main'
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod

      - run: CGO_ENABLED=0 go test -run ^$ -benchmem -bench=. ./...

  race-tests:
    if: github.event_name != 'push' && github.ref != 'refs/heads/main'
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod

      - name: Race tests
        run: go test ./... -race

  unit-tests:
    if: github.event_name != 'push' && github.ref != 'refs/heads/main'
    uses: ./.github/workflows/unit-test.yaml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  unit-tests-coverage:
    uses: ./.github/workflows/unit-test.yaml
    with:
      coverage: true
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
      token: ${{ secrets.GITHUB_TOKEN }}
