name: Unit test

on:
  workflow_call:
    inputs:
      coverage:
        type: boolean
        description: 'Run coverage tests'
        required: false
        default: false
    secrets:
      codecov_token:
        description: 'Codecov token'
        required: false
      token:
        description: 'GitHub token'
        required: false

jobs:
  unit-tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: go.mod

      - name: Unit tests
        if: '!inputs.coverage'
        run: |
          go install github.com/jstemmer/go-junit-report/v2@latest
          go install github.com/vakenbolt/go-test-report@latest
          env CGO_ENABLED=0 go test -v ./... 2>&1 > out.txt || true
          env CGO_ENABLED=0 go test -v ./... -json 2>&1 > json-out.txt || true
          cat out.txt | go-junit-report -out report.xml -iocopy
          cat json-out.txt | go-test-report -o report.html

      - name: Unit tests coverage
        if: inputs.coverage
        run: |
          env CGO_ENABLED=0 go test -v ./... -coverprofile coverage.out -coverpkg=./... -covermode atomic

      - uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5
        if: always() && inputs.coverage
        with:
          token: ${{ secrets.codecov_token }}
          fail_ci_if_error: true

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always() && inputs.coverage
        with:
          name: coverage
          path: coverage.out
          if-no-files-found: error
          retention-days: 30

      - name: Publish Test Report
        if: always() && !inputs.coverage
        uses: mikepenz/action-junit-report@3585e9575db828022551b4231f165eb59a0e74e3 # v5
        with:
          report_paths: "report.xml"
          require_tests: true
          check_retries: true
          detailed_summary: true
          fail_on_failure: true
          token: ${{ secrets.token }}
          check_name: Unit Tests

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always() && !inputs.coverage
        with:
          name: test-report-xml
          path: report.xml
          if-no-files-found: error
          retention-days: 30

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always() && !inputs.coverage
        with:
          name: test-report-html
          path: report.html
          if-no-files-found: error
          retention-days: 30
